services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
